---
- project:
    templates:
      - openstack-python36-jobs
      - openstack-python37-jobs
      - publish-tox-docs-infra
    check:
      jobs:
        - elastic-recheck-tox-queries:
            voting: false
        - openstack-tox-pep8
        - openstack-tox-py27
    gate:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py27

- job:
    name: elastic-recheck-tox-queries
    parent: tox
    description: |
      Run test for elastic-recheck project.

      Uses tox with the ``queries`` environment.
    vars:
      tox_envlist: queries
